name: Daily model monitoring

on:
  schedule:
    - cron: '17 6 * * *'
  workflow_dispatch: {}

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitoring
        run: |
          python - <<'PY'
          import subprocess, sys
          r = subprocess.run([sys.executable, 'src/utils/monitor_model.py'])
          sys.exit(r.returncode)
          PY

      - name: Upload monitor reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monitor-reports
          path: data/logs/monitor

      - name: Create issue on alert
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: 'Model monitoring alert'
          content-filepath: data/logs/monitor/latest.json
          labels: monitoring, alert


